### ISSUE TITLE
To clear

### ISSUE THREAD

**Issue by artemisholmes** [faiyazchowdhury/smart-cards#3]
Im afraid to say its too clear. Your variable names let the reader know exactly what it is it does. What have we always talked about? a, b, c - those variable names are simple and easy to use and make sure you don't understand your own code a week after you've written in it. Come on Faiyaz!!

**Comment by faiyazchowdhury** [comment]
Haha, the code is public for a reason :P. I want people to see and make changes.

**Comment by faiyazchowdhury** [comment]
Haha, the code is public for a reason :P. I want people to see and make changes.
